### ISSUE TITLE
[BUG] [0.9.0] Mowzie's Mobs Naga Crash

### ISSUE THREAD

**Issue by lonelymaw** [crummish/Crumbs#3]
**Describe the bug.**
Occasional server crashes caused by Mowzie's Mobs's attempting to spawn Naga entities in the overworld.

**What is the expected behavior?**
Nagas would be spawned in the world.

**What is the current behavior?**
Server crashes occur when Mowzie's Mobs attempts to spawn a Naga.

**How can the bug be reproduced?**
Attempt to spawn a Naga.

**Provide log files.**
```[01:40:56] [Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'mowziesmobs:naga'
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:305) [EntityEntryBuilder$ConstructorFactory.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:291) [EntityEntryBuilder$ConstructorFactory.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68) [EntityEntry.class:?]
	at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:655) [anh$c.class:?]
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:141) [anb.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:203) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoSuchFieldError: dc
	at com.bobmowzie.mowziesmobs.server.entity.naga.EntityNaga.<init>(EntityNaga.java:223) ~[EntityNaga.class:?]
	... 15 more
[01:40:56] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:149) ~[anb.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:203) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more
```

**Solutions?**
Mowzie's Mobs has [apparently resolved this issue after version 1.5.4.](https://minecraft.curseforge.com/projects/mowzies-mobs/files/2699705) Disable Naga spawns and/or update the mod.

**Comment by lonelymaw** [comment]
Fixed in Mowzie's Mobs update.
