### ISSUE TITLE
[BUG] [0.9.0] Unable to profile oregen for JER

### ISSUE THREAD

**Issue by lonelymaw** [crummish/Crumbs#8]
**Describe the bug.**
Using the `/profile 1000 all` command, or any variant of it, causes an immediate server crash.

**What is the expected behavior?**
A world generation profile file should be generated by JER after indexing each dimension.

**What is the current behavior?**
An immediate server crash occurs.

**How can the bug be reproduced?**
Run `/profile 1000 all` in a singleplayer world.

**Provide log files.**
```
Description: Exception in server tick loop

java.lang.NullPointerException
    at com.latmod.yabba.YabbaEventHandler.tickServerWorld(YabbaEventHandler.java:130)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_831_YabbaEventHandler_tickServerWorld_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```

**Solutions?**
The bug appears to be caused by [YABBA.](https://minecraft.curseforge.com/projects/yabba) Consider disabling before performing profile. However, upon testing, this still does not generate a proper profile.

**Comment by lonelymaw** [comment]
Fixed in commit 60f4c814b56ba625e87823f4dc1dc0b27c24e382
